spring:
  freemarker:
    cache: false
    suffix: .flt
  datasource:
    url: jdbc:mysql://192.168.158.222:3306/code_generator?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 365373011
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
server:
  port: 5600
